export const ACTION_TYPE = {
	APP: { LOADING: 'APP/LOADING' },
	USER: { LOG_USER: 'USER/SET_USER', LOG_OUT: 'USER/LOG_OUT' },
	ROOMS: { FETCH_ROOMS: 'ROOMS/FETCH_ROOMS' },
	BOOKINGS: {
		FETCH_BOOKINGS_USER: 'BOOKINGS/FETCH_BOOKINGS_USER',
		SET_BOOKING: 'BOOKINGS/SET_BOOKING',
		DELETE_BOOKING: 'BOOKINGS/DELETE_BOOKING',
	},
};
