export const ACTION_TYPE = {
	APP: { LOADING: 'APP/LOADING' },
	USER: { LOG_USER: 'USER/SET_USER', LOG_OUT: 'USER/LOG_OUT' },
	ROOMS: {
		FETCH_ROOMS: 'ROOMS/FETCH_ROOMS',
		UPDATE_ROOM_BOOKINGS: 'ROOMS/UPDATE_ROOM_BOOKINGS',
		DELETE_ROOM_BOOKING: 'ROOMS/DELETE_ROOM_BOOKING',
		UPDATE_ROOM: 'ROOMS/UPDATE_ROOM',
	},

	BOOKINGS: {
		FETCH_BOOKINGS_USER: 'BOOKINGS/FETCH_BOOKINGS_USER',
		SET_BOOKING: 'BOOKINGS/SET_BOOKING',
		DELETE_BOOKING: 'BOOKINGS/DELETE_BOOKING',
	},
};
